# Site settings
title: Jekyll / OpenAPI
description: A starter Jekyll site for use with GitHub Pages. Includes Bootstrap baked right in.
baseurl: "/jekyll-openapi" # the subpath of your site, e.g. /blog
url: "https://robertlove.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - assets/js/bootstrap.min.js
  - assets/js/jquery.min.js
  - assets/js/popper.min.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
